### ISSUE TITLE
Declarative syntax for focus looping

### ISSUE THREAD

**Issue by jihyerish** [WICG/spatial-navigation#1]
In the initial proposal for `nav-loop` which specifies an ability about the focus looping, it didn't regard the looping for each axis separately.
@frivoal pointed out considering define the focus looping for each axis.

How about adding values to nav-loop for it? Something like:
```css
nav-loop: auto | repeat | repeat-x | repeat-y | no-repeat
```
Each value means:
- repeat: The spatial focus navigation loops both horizontally and vertically.
- repeat-x: The spatial focus navigation loops only horizontally.
- repeat-y: The spatial focus navigation loops only vertically.
- no-repeat: The spatial focus navigation doesn't loop.

or having separate properties can be another possibility for this: 
```css
nav-loop-x: auto | repeat | no-repeat
nav-loop-y: auto | repeat | no-repeat
```

**Comment by frivoal** [comment]
I suspect it may be fairly typical in a vertically scrolling document to want the focus to wrap from the left side to the right one (and vice versa), but not from the top to the bottom. The former is a convenient shortcut, but the later could be disorienting.

The suggestion by @jihyerish would address that, so I am  supportive.

However, I think the API suggested in https://github.com/lgeweb/spatial-navigation/issues/6 could let authors build this on their own. So maybe we should do that first, and come back to this when we have more data about what authors commonly try to achieve.

**Comment by cynthia** [comment]
Vertically wrapping around seems like it would only make sense in very specific contexts (e.g. vertically laid out menus) - in a document context this just doesn't sound natural.

**Comment by frivoal** [comment]
Issue #6 has been closed in favor of the API of issue #2. I'm still in favor of getting that API first, experimenting with it, and coming back to this topic later.

**Comment by anawhj** [comment]
I think `nav-loop` doesn't seem a primitive feature for the spatial navigation. It could be covered by the relevant events and DOM methods. If we can draw a essential use case that should use kind of 'nav-loop' property later, this issue would be able to be discussed at that time.

**Comment by jihyerish** [comment]
@anawhj 
Yes, I agree. That's why we marked this issue with the label "Level 2".

**Comment by frivoal** [comment]
[Example 7](https://wicg.github.io/spatial-navigation/#loop) Now covers how to add this behavior in Javascript.

----

Closing this issue, as we do not plan to address it from a syntax point of view in level 1 (keeping the "level 2" label, so that we can find it later).
