### ISSUE TITLE
[css-nav-1] Improve the distance function

### ISSUE THREAD

**Issue by jihyerish** [WICG/spatial-navigation#114]
The distance function in the spec which measures the distance between two elements causes unexpected focus movement.
It needs to consider:
- Multiple candidate elements are adjacent to the starting point element (currently focused element)
- Transformed elements
- The element with rounded corner

So the function needs some experiment for getting the more reasonable result and simplifying.

Also, the function in the polyfill doesn't match exactly with the spec; it needs to be fixed.

**Comment by frivoal** [comment]
Issue migrated to w3c/csswg-drafts#3384
