### ISSUE TITLE
[css-nav-1] Tweak the distance function to prioritize elements that are aligned

### ISSUE THREAD

**Issue by frivoal** [WICG/spatial-navigation#122]
The current distance function behaves somewhat strangely, mostly due to:
* measuring edge to edge, which does not help decide which element to go to when two targets are at the same distance from the source's edge, even if one is fully in aligned, and the other is not
* The `B` factor in the formula penalizes elements which are aligned, in a way that is not fully compensated by `C`. Both in combination seem to favor elements at 0 or 90 degrees over those at 45 degrees, which does not seem justified.

We should:
* Switch from measuring from edge to edge to measuring from center to edge
* Drop the B factor, and possibly the C factor as well.

**Comment by cynthia** [comment]
I've tried a quick and dirty prototype that computes the delta between the desired direction's reference angle and the angle between the currently focused element's centroid and the candidate element's centroid with an arctangent2, and it seems to improve performance a bit. @jihyerish knows how the strawman algorithm works, but the weights and magnitude have to be scaled to match the other ABCD scores in the distance computation phase.

Whether or not you factor this in is entirely up to you, but it seems to help.

**Comment by jihyerish** [comment]
@hugoholgersson 
Yes, I agree with you. Measuring the distance depending on the centroid can achieve the more precise result.

I've been also considering the case that you described above. 
To cover this case, the span element is considered as the two [fragment](https://www.w3.org/TR/css-break-3/#box-fragment)s.
So inside the element's border box, the closest fragment from the edge which is on the direction of the navigation will be selected to use for calculating the distance.

In your example, if the user presses the down arrow key, from the "XXXXXXX" fragment in the second line the distance value will be calculated.

**Comment by hugoholgersson** [comment]
Taking the centroid of that fragment, you mean?

**Comment by jihyerish** [comment]
@hugoholgersson Yes. Because of that, it needs to be defined which fragment to take depending on the input direction.

**Comment by cynthia** [comment]
Probably an edge case worth noting that a horizontally equally sized multiple fragment would need to be handled by using the centroid of the vertical extremas.

**Comment by hugoholgersson** [comment]
@cynthia could you give an ASCII example? (How do you define "vertical extremas"?)

I can imagine one case where a focusable, C, becomes unreachable (?) when going up/down between A and B:

~~~
BBBBBBBBBB
.........B
.....CC...
.........A
AAAAAAAAAA
~~~

**Comment by frivoal** [comment]
Issue migrated to w3c/csswg-drafts#3388
