### ISSUE TITLE
scrollIntoView after focus.

### ISSUE THREAD

**Issue by themihai** [WICG/spatial-navigation#141]
I'm developing a remote controlled app(flex-box image gallery app) and to reduce incremental and unnecessary  "small scrolls" I've patched the polyfill and added scrollIntoView after focus so that the client/ua can get better/complete visibility of the focused element. 

https://github.com/WICG/spatial-navigation/blob/0bd2d5cc4888a451d6551732c59aefa2ea74d21d/polyfill/spatnav-heuristic.js#L252

```
   // When bestCandidate is a focusable element and not a container : move focus
      /*
        * [event] navbeforefocus : Fired before spatial or sequential navigation changes the focus.
        */
      createSpatNavEvents('beforefocus', bestCandidate, dir);
      bestCandidate.focus();
      +++bestCandidate.scrollIntoView({behavior: "smooth", block: "center"});
```

**Comment by jihyerish** [comment]
Hi, Thanks for reviewing and using the polyfill!
This polyfill aims to match with the current [spec of Spatial Navigation](https://drafts.csswg.org/css-nav-1/#dom-element-spatialnavigationsearch).

Applying the smooth scrolling isn't in the spec, and I think it's the UA-dependant feature.
So, could you use [spatialNavigationSearch()](https://drafts.csswg.org/css-nav-1/#dom-element-spatialnavigationsearch) API in the polyfill for that feature?

You can use like this:

```
document.addEventListener("navbeforefocus", function(e) {
    e.preventDefault();

    if (e.dir === "forward" || e.dir === "backward") {
        e.dir = "top";
    }

    var t = e.relatedTarget;
    while (t.isSameNode(t.getSpatialNavigationContainer())) {
        var areas = t.focusableAreas();

        if (areas.length === 0) { break; }

        t = t.spatialNavigationSearch({
            dir:  e.dir,
            candidates: areas
        });
    }
    t.scrollIntoView({behavior: "smooth", block: "center"});
});
```

**Comment by themihai** [comment]
spatialNavigationSearch works great! thanks!
