### ISSUE TITLE
execute spatialNav inside closed shadow dom

### ISSUE THREAD

**Issue by themihai** [WICG/spatial-navigation#142]
I'm trying to run spatialNav polyfill inside a closed custom element/shadow dom. It think as it is the polifill cannot be used in a closed shadow dom so I've patched it so that I can pass  the shadow dom as 'document' param.
```
:11--- (function () {
:11+++function spatNavInit(window, document) {
```

I get focus inside the shadow dom but navigation  fails to work. Below is the error ( from console). It seems the lib is looking for document.body but there is no 'body' tag in custom elements/shadow dom.

```
Uncaught TypeError: Cannot read property 'children' of undefined
    at HTMLHtmlElement.focusableAreas (spatnav-heuristic.js:495)
    at navigate (spatnav-heuristic.js:217)
    at spatnav-heuristic.js:80
```

```
:495
      // Find focusable areas among this
      children = container.children;
      .....
:217
      const candidates = filteredCandidates(eventTarget, container.focusableAreas(), dir, container);
    ....
:80    
    navigate(dir);
   ...
```

```
class ViewMedia extends HTMLElement {
   constructor() {
      super();
      const shadow = this.attachShadow({mode: 'closed'});
      // get html body we want to inject
      const val = this.getAttribute('data-value'); 
        shadow.innerHTML =  val;
        // initiate our custom element stuff
        this.watch = NewWatch(shadow); 
        // store the shadow dom for later usage
          this.shadow = shadow;
      }
      // watch for attribute change
    static get observedAttributes() {
        return ['data-expanded'];
    }
    attributeChangedCallback(name, oldValue, newValue) {
        console.log('name ', name, 'old value', oldValue, 'new val ', newValue);
        if (name === 'data-expanded' && newValue === 'true'){
           // focus within the shadow dom element.
            this.watch.focus(); 
            // init spatial navigation 
            spatNavInit(window,  this.shadow); 
        }
      }
}
```

**Comment by jihyerish** [comment]
> I get focus inside the shadow dom but navigation fails to work. Below is the error ( from console). It seems the lib is looking for document.body but there is no 'body' tag in custom elements/shadow dom.

The closed shadow dom cannot be accessible with JS in general.
I believe that problem will be solved if [the spatial navigation spec](https://drafts.csswg.org/css-nav-1/) which is the referencing spec of this polyfill is implemented in the browser in the near future! : )
