### ISSUE TITLE
Problem with navigating with sticky navbar, and scrolling body

### ISSUE THREAD

**Issue by abhishiv** [WICG/spatial-navigation#151]
Hello

Thank you very much for a much needed library/polyfill.

I have a little problem.

Code here: https://output.jsbin.com/celekuh

![ezgif-4-11ce399ba2fe](https://user-images.githubusercontent.com/37350/51467051-9d6adb00-1d91-11e9-91d5-e0702f3baad8.gif)

As you can see, once the focus moves to top section in the viewport, pressing up moves the focus to nav, and then pressing up again just scrolls the page. This might be correct according to the spec, but from UX point of view maybe is counter intuitive.

I also tried using `--spatial-navigation-contain: contain` on container wrapping the sections, however that also doesn't change anything. In this case overflow is applied on body, because otherwise scrolling is very jaggery on touch devices.

Since sticky navbars are a common enough UI pattern, any ideas how I can make it work?

**Comment by jihyerish** [comment]
Yes, I aware of this scenario can often happen in the real page. 
The reason for this behavior is :
(1) `<a tabindex="0" href="/">home</a>` is currently focused element.
(2) The up arrow key is pressed.
(3) There is no element upward from the currently focused element.
(4) The container of the currently focused element is document, and it can be scrolled, 
     so pressing the up arrow key works for scrolling.

Step (3) - (4) is the common behavior in the spatial navigation and also the general rule of the spec.

However, to solve this issue, step (4) may don't occur when the currently focused element is a sticky positioned element or descendant of a sticky positioned element.
This approach is the spec point of view, so the current polyfill need to be updated depending on the changes in the spec.
Thanks for your valuable feedback, and I'll let you know if there is a progress about this!

**Comment by abhishiv** [comment]
Hey @jihyerish 

Many thanks for your reply.

Just to be clear, I meant that in this case when the focus is on the topmost section in the viewport, pressing up should move the focus the section just above it instead of moving it to nav, and repeat this on up-key-presses until body has been completely scrolled. Then pressing up can move focus to nav. That I think is more intuitive from UX point of view.
