### ISSUE TITLE
Spatial Navigation Containers

### ISSUE THREAD

**Issue by jervisfm** [WICG/spatial-navigation#189]
The current implementation for the isContainer check in part determines whether an element is a container by seeing if it's a scroll container. 

https://github.com/WICG/spatial-navigation/blob/efd441869a19a39fe0c3c9281f2c7730cc78b660/polyfill/spatial-navigation-polyfill.js#L599-L624

The implementation for isScrollContainer follows the CSS spec by treating anything that could potentially be scrolled as a scroll container. https://drafts.csswg.org/css-overflow-3/#overflow-properties.

In practice, this can cause issues whereby one wants to use 'overflow:hidden' property to hide overflow and also not have spatial navigation treat those elements are containers to look for focus within, potentially leaving one stuck if there are no visible focus candidates on screen.

Agree that the implementation is per CSS spec but was wondering if there is any room for customization to not consider elements with 'overflow:hidden' as containers.

**Comment by jervisfm** [comment]
Hi,

Just wondering if you had a chance yet to consider this. Is such a change reasonable ?

**Comment by jihyerish** [comment]
Hi @jervisfm, sorry for the late reply.
Yes, your suggestion is reasonable, I agree that the overflowing element with `overflow: hidden` shouldn't be scrolled by spatial navigation.

I've made the change about this in polyfill by https://github.com/WICG/spatial-navigation/pull/200.
