### ISSUE TITLE
Does the `candidates` attribute of `SelectSpatNavBestCandidateOptions` need to be required?

### ISSUE THREAD

**Issue by frivoal** [WICG/spatial-navigation#20]
It seems a way to know the best candidate just with the direction argument would be convenient (e.g. `elm.selectSpatNavBestCandidate("right");`),
but it may also be confusing:
Would this be expected to search only within the innermost spatnav container,
or to reproduce the full logic of running the <a>spatial navigation steps</a>,
and if so, does that include scrolling (probably not), or a special return value to indicate
that scrolling would have happened (maybe)?

Maybe we need a separate method for that.

**Comment by hugoholgersson** [comment]
I wonder what authors would need most often: Finding all possible candidates or just the one that spatnav would go to next.

On the other hand, I guess we could assume that most authors already know their own DOMs and the set of elements within it that they consider for navigation...? With that assumption, when would they need our API? They can already override the built-in heuristics by intercepting `beforenav`.

**Comment by frivoal** [comment]
> I wonder what authors would need most often: Finding all possible candidates or just the one that spatnav would go to next.

I guess it depends what you're trying to do. The APIs as proposed now are meant to be low level and stay as close as possible to the underlying processing model, so that if you're trying to tweak things or to write polyfills for possible extensions of spatnav, you do have to reinvent the parts you're happy with.
So, for instance if you're fine with the way the browser determines candidates, but you just want a different distance function (something like https://github.com/WICG/spatial-navigation/blob/master/explainer.md#nav-rule-property-cssui4), you'd intercept the `navbeforefocus` event, use the `findSpatNavCandidates()` method as it is to get the set of candidates, and do your thing within that set.

So, for polyfils and similar purposes, I think the current APIs are at the right level.

In addition, having some higher level APIs is probably a good thing two. Whether that should be through making these APIs smarter if you omit (or specify) certain parameters, or through separate APIs, I am not 100% sure.

For instance, @therealglazou suggested something like this:
`document.querySelector( "p::spatnav(down)" )`

That seems interesting to me, but I'd like to hear some concrete use cases of what people are trying to do with the API (other than polyfils) to make sure we design for what people actually need, rather than what we imagine them to need.

**Comment by bkardell** [comment]
where was `document.querySelector( "p::spatnav(down)" )` suggested? did the suggestion include more words than that, for example, explaining what it would do?  I'm not sure how to parse that?

**Comment by anawhj** [comment]
In our approach for the spatial navigation, we have a base line (aka. heuristic algorithm) mechanism specified in [SpatNav spec](https://wicg.github.io/spatial-navigation/#heuristics), to manage the key-based focus navigation using arrow(LRUD) keys. In addition, we hope to make authors override the heuristic algorithm to re-calculate what the next focused element is for the specific purpose.

The candidates information could be used as one of the required features when overriding the base line, but I expect there are a few real use cases that should use the candidates information according to the investigation until now. I would suggest that how about supporting the candidates information only in a scope of `navbeforefocus` event first. If it seems very useful in several context for authors, we can support the candidates in the other ways such as DOM methods, pseudo elements later. In terms of the first phase(level) of the spatial navigation, what the most important primitive is seems what we should focus on.
