### ISSUE TITLE
Browser Support seems to be wrong

### ISSUE THREAD

**Issue by cztomsik** [WICG/spatial-navigation#213]
Or it's outdated or misleading because I'm on Chrome 77 and I don't see any `el.focusableAreas()`

**Comment by anawhj** [comment]
I'm also on Chrome 77 and it works well.
Could you check it via Chrome developer tool(F12) at the following demo link.
https://wicg.github.io/spatial-navigation/demo/
(In Console tab, you can input $0.focusableAreas().)

**Comment by cztomsik** [comment]
The polyfill works but the spec is not implemented in any browser, and there's no information about this either (status of the spec, not the polyfill), so it looks like this is something we can use already but we can't and it's not even 100% decided how it should work so it could even change at any time.

That said, I appreciate the work, really, thanks. It's just that I was misleaded by this repo.

I'd personally leave a small note or link to the RFC or something (couldnt find it)

**Comment by anawhj** [comment]
Ah.. I got your point and agree on it. It could be misleading so I modified the description as follows:
https://github.com/WICG/spatial-navigation/commit/c2239edfa843ede60b34d6331197d7d0dffbe47d#diff-04c6e90faac2675aa89e2176d2eec7d8

As you mentioned, the spec hasn't been implemented in any browser. If any progress on it, we will add the information to README.md. I put it to README.md as follows:
https://github.com/WICG/spatial-navigation/commit/58dbd49f94a327d8f7c49bba66cdaeed5af83d28#diff-04c6e90faac2675aa89e2176d2eec7d8

If you'd like to put some opinion to the spec, you can report it via WICG/spatial-navigation issues or w3c/csswg-drafts issues with a `css-nav` label. You could also make a PR directly for the addition into the spec in w3c/csswg-drafts. Thank you for the consideration.

**Comment by cztomsik** [comment]
Awesome, thank you :-)

And also, thanks for your work, it's really great that there's a polyfill for this.

**Comment by anawhj** [comment]
Thank you for the kind words. If you don't have any comment, please close the issue :)
