### ISSUE TITLE
spatial navigation polyfill does not check the state of unrelated modifier keys like Ctrl/Meta/Alt...

### ISSUE THREAD

**Issue by Yaffle** [WICG/spatial-navigation#218]
...when checking if the navigation should be triggered

**Comment by anawhj** [comment]
Do you mean that the spatial navigation shouldn't work if the unrelated modifier keys are pressed with arrow keys at the same time?

If so, you can simply put a small code with `e.getModifierState(..)` at the following place.
https://github.com/WICG/spatial-navigation/blob/master/polyfill/spatial-navigation-polyfill.js#L83

**Comment by Yaffle** [comment]
@anawhj , Thanks, I have created a pull request -  https://github.com/WICG/spatial-navigation/pull/219
