### ISSUE TITLE
How would screen reader users use spatial navigation?

### ISSUE THREAD

**Issue by Malvoz** [WICG/spatial-navigation#223]
In browse mode (which I believe is default in all/most screen readers, at least in NVDA) the arrow keys are used to read text in a certain direction. I don't know if the typical screen reader user knows how and when to switch between the different modes but it's currently not possible to navigate the demo pages using the arrow keys in browse mode.

Of course, a screen reader user may not even need to navigate documents this way...

**Comment by jihyerish** [comment]
You can switch the keys instead of arrow keys using `window.navigate()` API for spatial navigation.
The corresponding demo is :
https://wicg.github.io/spatial-navigation/demo/#navigate

**Comment by Malvoz** [comment]
Okay, to try to make a long story short, the [Maps for HTML Community Group](https://www.w3.org/community/maps4html/)'s goal is more or less: declarative maps for the web, and I think we're envisioning panning to be controlled using arrow keys. The current situation in [popular web map tools](https://maps4html.org/HTML-Map-Element-UseCases-Requirements/examples/create-map.html) is that none of them are pannable without switching from browse mode, which I _think_ is problematic (how do users know to switch mode?). But I suppose because arrow keys (with potential modifier keys) for _standard_ per-element panning (and spatial navigation) would be UA-defined there'd be no need for switching keys using `window.navigate()` to enable these types of navigation as screen readers would have predefined and configurable modifiers. Although it'd be nice if the default didn't require modifier keys as I think arrow keys alone is more intuitive, but reading https://github.com/w3c/csswg-drafts/issues/5683 I learned that specs can't put such requirements on browser interfaces.

Thanks @jihyerish.

**Comment by jihyerish** [comment]
@Malvoz yes, I aware of Maps for HTML Community Group and tried to combine the concept of it with Spatial navigation.
But I came up with the final goals of them are quite different. (The main use cases of the spec are different).
Thank you for your interest and input! It was interesting for me to look at the progress on Maps for HTML thanks to you!
