### ISSUE TITLE
Rephrase "select the best candidate" to "find closest focusable area"?

### ISSUE THREAD

**Issue by hugoholgersson** [WICG/spatial-navigation#30]
The word _select_ makes me think of text selections. 

_Best_ is a vague word. The _best_ element is always the _closest_ element, right?

Maybe calling the JS method something like `closestFocusableArea()` would help authors understand the API better?

**Comment by frivoal** [comment]
> The best element is always the closest element, right?

Sort of. It is "the closest", but according to a somewhat weird distance function that takes direction and overlap into account. (whether the current distance function is idea is another interesting question, but the point remains that it is not necessarily a simple euclidean distance).

Not sure whether it is better to say "best" and let people wonder "best based on what", or to say closest and give an approximately correct idea, but risk have people assume it means closest by euclidean distance, which is not what it is.

**Comment by frivoal** [comment]
> The word *select* makes me think of text selections.

Right, that seems unfortunate indeed. I attempting to use it to mean "narrow down from an explicit list", to reinforce the idea that it is step 2, after finding the candidates. But suggesting text selections is possibly worse.

**Comment by frivoal** [comment]
closed by https://github.com/WICG/spatial-navigation/commit/aadb72d9f9193609bd4243fa40affddb5573987e
