### ISSUE TITLE
Remove `navbeforescroll`?

### ISSUE THREAD

**Issue by hugoholgersson** [WICG/spatial-navigation#36]
Conceptually I see spatnav as a key-hook that runs in the browser just before arrow-key scrolling. If spatnav didn't find anything to focus, it lets the standard arrow-key scrolling do its job.

`navnotarget` could be used to signal: "spatnav's search failed, here's your chance to do something before we hand over control to the arrow-keys".

When handling `navnotarget`, authors would still be able to find out, by looking at the focused element's container's overflow, if a scroll is about to happen or not.

**Comment by anawhj** [comment]
`onnavigate` event seems the better approach than only supports of `navbeforefocus` and `navnotarget`. We can discuss with the issue in #32 as a single thread. How about this?

In addition, both behaviors (scrolling and none) would have to be classified for authors. I prefer to support the three types in a same level.

**Comment by hugoholgersson** [comment]
> In addition, both behaviors (scrolling and none) would have to be classified for authors. 

Is it really necessary to tell authors when spatnav is about to do arrow-key-scrolling? I think authors could get this kind of information by looking at the page layout (standard JS) from an `onnavigate`-handler.

If we don't explicitly have to tell authors when spatnav is about to do arrow-key-scrolling, then the  `onnavigate`-event could be simplified... I'd like the `navigate`-event to be as simple as possible because I'm thinking, in the future, that event could also be sent before sequential (= tab-key) navigation. The simpler it is, the higher chance I will become implemented across browsers.

**Comment by hugoholgersson** [comment]
> How about this use case? 

That's a good use case. Thanks! But isn't vanilla JS + a slim `onnavigate` capable of doing this? 

In this use case, a slim `navigate`-event would be sent with `relatedTarget = null` because no event will be focused by spatnav (spatnav will only trigger an arrow-key scroll). When an author sees the `null`, she could check the navigate-event's target's enclosing scroller. If it can scroll, that means spatnav will soon scroll it. With this information, she can decide to move focus manually with the same method: preventDefault() + betterElement.focus().

**Comment by anawhj** [comment]
Right, theoretically. The additional procedures for checking `relatedTarget` and a current scroll offset seem inconvenient, though I'm not in favor of vanilla JS.

**Comment by hugoholgersson** [comment]
>  I'm not in favor of vanilla JS.

Right, but its hard to predict the popularity and usefulness of `navbeforescroll`. And since it can be pollyfilled via `navigate`, let's not include it in the spec's first round? 

> As you mentioned, navbeforescroll can't be used in the sequential navigation.

Yes. I believe we, at this point, only should add events and APIs that benefit and work with both spatial and sequential navigation... I believe that will make this API more popular and attractive.

**Comment by frivoal** [comment]
Based on the discussion above, and using [example 5](https://wicg.github.io/spatial-navigation/#focus-only), [example 6](https://wicg.github.io/spatial-navigation/#delegation), and [example 7](https://wicg.github.io/spatial-navigation/#loop), and in agreement with @jihyerish, I am closing #32 and #36 as *no change*.

Further discussions with DOM people or the browser community may result in additional API changes, but for now, this is the design we're going with.
