### ISSUE TITLE
nextFocusMove() instead of selectSpatNavBestCandidate() and sequentialNavSearch()?

### ISSUE THREAD

**Issue by hugoholgersson** [WICG/spatial-navigation#37]
Could we generalize `element.selectSpatNavBestCandidate()` and `element.sequentialNavSearch()` into `element.nextFocusMove(direction)`? 

`direction` would be from a `NavigationDirection`, that includes both sequential- and spatial navigation's steps; forward, backward, up, down , left, right.

We would then lack an API for asking "Which one, out of these focuables, would spatnav go to?", but we could instead ask "Which is **the** focusables spatnav/tabnav would go to?". I think the latter is more useful.

**Comment by frivoal** [comment]
Fundamentally, that seems like a good idea. In the basic version, both just take a direction, and that's it.

That said, both `selectSpatNavBestCandidate` (current spec) and `spatNavSearch()` (from Pull Request #38) allow for options that `sequentialNavSearch()` does not.

Would it work if we merged the two, and for the argument take either:
* just a direction, which can be any of forward, backward, up, down , left, right
* an option object, with a direction which can be up, down , left, right (but not forward or backward) and the other attributes

It seems it would not be great to allow backward or forward to be specified in combination with options meant for spatnav, and have these options be ignored.

**Comment by hugoholgersson** [comment]
> an option object, with a direction which can be up, down , left, right (but not forward or backward) and the other attributes

What other attributes? What options relate to spatial- but not to sequential navigation?

> just a direction, which can be any of forward, backward, up, down , left, right

I'd prefer it to just take "direction". That seems simpler...?

**Comment by frivoal** [comment]
> What other attributes? What options relate to spatial- but not to sequential navigation?

If you look at the existing ones, there are options to chose which element to use as a container to search in, or to pass in the list of candidates directly. There's also been a suggestion to pass in a custom "distance" function that it would use to chose what is the closest.
Even if we end up changing the parameters that we currently have, it remains true that the way you search spatially and the way you search sequentially are different, so if they are going to take parameters, which might be debatable in level 1 but certainly will happen eventually, then they will take different parameters

**Comment by frivoal** [comment]
Based on the argument above, I think we should not merge. Even if we did subset things enough so that a version 1 would take the same arguments, future extensions would not. I've discussed with @jihyerish and she agrees, so closing this issue.
