### ISSUE TITLE
@rule for arrow-key-behavior?

### ISSUE THREAD

**Issue by frivoal** [WICG/spatial-navigation#5]
Similarly to issue #4, it seems to me that `arrow-key-behavior` would be simpler and just as useful as an at-rule instead of a property.

**Comment by jihyerish** [comment]
I think this is the same issue with https://github.com/lgeweb/spatial-navigation/issues/3.
I agree that for enabling the spatial focus navigation, an at-rule could be easier to use than a property.

**Comment by frivoal** [comment]
It is the similar to #3, as both suggest using an at-rule to enable spatial navigation, but they suggest different at-rules.

We may need to agree separately about whether an at-rule is the best approach (I think we agree already), and what the syntax and semantics of that at-rule should be (more discussion seems needed).

**Comment by frivoal** [comment]
I think this issue can be merged with #3, is that OK with you @jihyerish ?

**Comment by jihyerish** [comment]
@frivoal Yes, sure. : )
