### ISSUE TITLE
Should finding candidates be recursive or not

### ISSUE THREAD

**Issue by frivoal** [WICG/spatial-navigation#63]
Currently, the spec says that **find candidates** works from 
>  the set of all the focusable areas that are descendants of [the container]

The polyfill, on the other hand, does not include the focusable areas that are themselves descendants of other focusable areas within the container. In other words, the spec is recursive, while the polyfill is not.

The difference can be observed in [this example](https://wicg.github.io/spatial-navigation/sample/heuristic_scrollable.html), by focusing the topmost blue box, and trying to go up. With the polyfill, it will no go any higher, while the spec would cause red box to be focused.

It seems that the behavior in the spec is preferable, but it there may also be a performance concern.

I lean towards considering this a bug in the polyfill, but discussion is welcome.

**Comment by jihyerish** [comment]
I think the behavior in the spec would be the right way.

As I mentioned on the #73, the focus can move inside the spatnav container even if its tabindex value is "-1".
I'll fix the current behavior of polyfill.

**Comment by frivoal** [comment]
Agreed, let's close this by fixing the polyfill.
