### ISSUE TITLE
spatial navigation starting point outside of the currently focused element.

### ISSUE THREAD

**Issue by frivoal** [WICG/spatial-navigation#68]
The spec and the polyfill behave differently when the spatial navigation starting point, set by a click, is outside of the currently focused element. In the spec, it is only taken into account if it is inside, and ignored otherwise. I the polyfill, it is always used.

**Comment by jihyerish** [comment]
What I understand about the starting point is like this:

- startingPoint: The currently focused **area** of a top-level browsing context. (Searching origin)
  - From the startingPoint, spatnav finds the best candidate depends on the direction.
  - It can be a node or a position
- spatial navigation starting point: The starting point that is specified by UA.
  - For example, if UA defines clicking the element can change the starting point, then the clicked element becomes

I have a question about this.

**1. Is it right that the eventTarget of spatnav can be both focusable and non-focusable?**

In the processing model of the spec, eventTarget is set by the startingPoint.
If the eventTarget is set by the node which contains the spatial navigation starting point, 
can the eventTarget be the non-focusable element?

**2. In the sentence of "outside of the currently focused element", does outside mean the area of the parent node of the document objects?**

**Comment by frivoal** [comment]
> What I understand about the starting point is like this:
> * startingPoint: [...]
> * spatial navigation starting point: [...]

Mostly, but note another difference, **spatial navigation starting point** is a definition, so it always means the same thing, which is what you said. On the other hand **startingPoint** is a variable in an algorithm. It starts as "The DOM anchor of the currently focused area of a top-level browsing context" (which is a node), but it can be changed to the **spatial navigation starting point** in step 2 of the algorithm, which doesn't have to be a node.

> 1. Is it right that the eventTarget of spatnav can be both focusable and non-focusable?

Yes, it can be either. For instance, `<body>` is generally non focusable, but it is the eventTarget when nothing in particular is focused.

> 2. In the sentence of "outside of the currently focused element", does outside mean the area of the parent node of the document objects?

This refers to step 1+2 of the [spatial navigation steps](https://wicg.github.io/spatial-navigation/#spatial-navigation-steps). So it means if the startingPoint (after step 1) is a scroller, and the initial starting point is a point inside the scroller (because the user clicked there, for example, then startingPoint is changed to the point where the user clicked. But if the UA has somehow set the initial starting point outside of the scroller which is focused, then this has no effect.

**Comment by frivoal** [comment]
> Oh, it seems like <body> is focusable in general.

Ah, that's true. Either way, if the currently focused element is a scroller, and inside the scroller there is a non focusable div, and the UA sets the initial starting point inside that div, then step 2 of the spatial navigation steps changes the starting point to that initial starting point, and step 3.else sets the eventTarget to the div.

**Comment by frivoal** [comment]
> Let `#box2` (`button` element with `id=box2`) is focused. (**initial starting point**)
> In this condition, 
> - if the user click `#container2` (`div` element with `id=container2`), 
>   the startingPoint doesn't change because `#container2` isn't a child element of `#box2`(**initial starting point**) nor focusable.
>   Then the user press the arrow down key, the focus moves to `#box3` (`button` element with `id=box3`)
> - if the user click `body`,
>   the startingPoint changes to `body`, because `body `is focusable in general.
>   Then the user press the arrow down key, the focus moves to `#box1` (`button` element with `id=box1`) because `#box1`  is the 1st focusable element within `body`.
> 
> Next up, let `body` is focused. (**initial starting point**)
> In this condition, 
> - if the user click `#container2` (`div` element with `id=container2`), 
>   the startingPoint changes to `#container2` because `#container2` is a child element of `body` (**initial starting point**).
>   Then the user press the arrow down key, the focus moves to `#box5` (`button` element with `id=box5`).
> 
> Are the expected result of three cases right?

Yes, that is correct.

I think maybe the first case ("if the user click #container2") will be different, because clicking on a non focusable element will remove the focus. But for example, if we use a browser that sets the spatial navigation starting point based on hover instead of click, that would be correct.

**Comment by jihyerish** [comment]
@frivoal 
Depending on our discussions above, I've made changes to the polyfill for fixing this issue.
Does the PR (https://github.com/WICG/spatial-navigation/pull/109) make a proper modification?

**Comment by jihyerish** [comment]
https://github.com/WICG/spatial-navigation/pull/109 fixed this issue, so I'll close this issue.
