### ISSUE TITLE
Should shadow dom roots be spatnav containers by default?

### ISSUE THREAD

**Issue by frivoal** [WICG/spatial-navigation#69]
I suspect they should, but opening the question for discussion.

**Comment by jihyerish** [comment]
I agree with this idea, but is the shadow host more suitable to be a spatnav container instead of the shadow root?
Because the shadow root cannot be reachable from the main DOM tree.

There are issues about when the focus moves inside and outside of the shadowDOM.
But when the shadow root (or shadow host) become a spatnav contain, the focus can manageable with APIs in spatnav spec.

**Comment by jihyerish** [comment]
Based on the discussion in Sydney, I think considering the shadow root as a spatnav container b default isn't mandatory.
These are the reasons for it:

* Spatial navigation behavior needs to be different for spatnav container and the shadow host when setting `tabindex=-1` on those.
   * Setting `tabindex=-1` on a shadow host removes the focusable elements in the shadow dom from the navigation order. 
      * Currently, sequential navigation works like this.
      * reference: https://github.com/w3c/webcomponents/issues/520
   * Even if setting `tabindex=-1` on a spatnav container, focus will move to the focusable elements inside the spatnav container.
      * This is because the focusable elements are searched from the closest spatnav container of the spatnav container with `tabindex=-1`.

* Main role of the default spatnav container is handling the offscreen focusable element.
   For my understanding, we define the default spatnav container to handle the focusable element which is out of the viewport.

**Comment by frivoal** [comment]
The discussion on `tabindex=-1` is a bit separate, so we'll treat that in another issue.

But as far as spatnav containers go, while it seems likely that you'd often want a shadow dom component to be a container, there's not particular reason that you'd always want that.

So it needs to remain under author control, and to do that, this means off by default, use the property to turn it on if needed, which is the way the spec is currently set up.

Closing as no change.
