### ISSUE TITLE
iframe demo bug

### ISSUE THREAD

**Issue by Malvoz** [WICG/spatial-navigation#80]
After navigating to https://wicg.github.io/spatial-navigation/sample/heuristic_iframe.html and then pressing the down key <s>until the last focusable object</s> (doesn't matter if I navigate all the way to the last object or not), then pressing up until returning to the first object - it renders the page unresponsive and the amount of CPU the page uses increase a ton.

I've been able to replicate this 3 times on Windows 10 using Chrome 67.0.3396.99.

**Comment by jihyerish** [comment]
@Malvoz Thanks for reporting this bug! I'll fix this ASAP.

**Comment by Malvoz** [comment]
This did not occur for any of the other samples by the way.
