### ISSUE TITLE
License for the Polyfill Library

### ISSUE THREAD

**Issue by jervisfm** [WICG/spatial-navigation#97]
Hi, 

I am just wondering - what is the code license (if any) for the Polyfill library under  https://github.com/WICG/spatial-navigation/tree/master/polyfill ?

Does it use the same LICENSE as https://github.com/WICG/spatial-navigation/blob/master/LICENSE.md ?

The wording on that file does not make it explicitly clear whether the license also applies to the code (and not just the specification). 

Thanks for any clarifications.

**Comment by jihyerish** [comment]
@jervisfm Thanks for asking this! You asked for a good point.
I've added the license of the polyfill.
 (https://github.com/WICG/spatial-navigation/blob/master/polyfill/LICENSE)

The polyfill is now under the MIT license.
